#!/system/bin/sh
#simplify mount rw and mount ro
#scripting wrote by forcystos - SDX - sdx-developers.com
#updated for samsunge epic by joeykrim - SDX - sdx-developers.com
#Modified by DRockstar for rootfs
case $1 in
rw)
  echo "Remounting /system (/dev/stl9) and rootfs in read/write mode"
  busybox mount -o remount,rw /system
  busybox mount -o remount,rw /;;
ro)
    echo "Remounting /system (/dev/stl9) and rootfs in read-only mode"
    busybox mount -o remount,ro /system
    busybox mount -o remount,ro /;;
*)
    echo "usage: remount rw   -or-   remount ro";;
esac
